import { AuthProvider } from "../_db/AuthContext";
import "./auth.css"
import { Inter } from 'next/font/google';

const inter = Inter({
  weight: ['100', '500'], // Inter weights (100 to 900)
  subsets: ['latin'], // Use the desired subset
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ fontFamily: inter.style.fontFamily}}>
        <AuthProvider>
        {children}
        </AuthProvider>
      
        </body>
    </html>
  )
}
