import { AuthProvider } from "../_db/AuthContext"; // Imports the AuthProvider to make authentication context available to child components.
import "./auth.css" // Imports CSS styles specific to the authentication layout and its pages.
import { Inter } from 'next/font/google'; // Imports the Inter font from next/font for optimized web font loading.

// Configures the Inter font with specific weights and subsets.
const inter = Inter({
  weight: ['100', '500'], // Specifies the font weights to be loaded (e.g., Light and Medium).
  subsets: ['latin'], // Specifies the character subsets to include (e.g., Latin characters).
});

// Metadata for the authentication pages.
export const metadata = {
  title: 'Next.js', // Sets the title for the pages within this layout.
  description: 'Generated by Next.js', // Sets the description for the pages.
}

// Defines the layout component for authentication-related pages (e.g., login, register).
export default function AuthLayout({
  children, // Props that will include the page content to be rendered within this layout.
}: {
  children: React.ReactNode // Type definition for children, expecting a React node.
}) {
  return (
    <html lang="en"> 
      <body style={{ fontFamily: inter.style.fontFamily}}>
        <AuthProvider>
        {children}
        </AuthProvider>
      
        </body>
    </html>
  )
}