import Header from "../components/header";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function HomeLayout({
  sidebar,
  feed
}: {
  children: React.ReactNode,
  sidebar: React.ReactNode,
  feed: React.ReactNode
}) {
  return (
    <html lang="en" style={{ height: "100%" }}>
      <body
        style={{
          display: "flex",
          flexDirection: "column",
          height: "100%",
          margin: 0
        }}
      >
        <Header />
        <div
          style={{
            display: "flex",
            flex: "1 1 auto", // Central section takes available space
            height: "100%", // Ensures this div has 100% height
          }}
        >
          {feed}
          {sidebar}
        </div>
        <footer
          style={{
            border: "solid thin black",
            marginTop: ".5rem"
          }}
        >
          All rights reserved
        </footer>
      </body>
    </html>
  );
}

