import Header from "../(components)/header"
import '@blocknote/core/fonts/inter.css';
import '@blocknote/mantine/style.css';
import { Inter } from 'next/font/google';
import "../global.css";


const inter = Inter({
  weight: ['100', '500'], // Inter weights (100 to 900)
  subsets: ['latin'], // Use the desired subset
});

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function UserLayout({
    children,
  }: {
    children: React.ReactNode
  }) {

    return (
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
          </body>
      </html>
    )
  }
  