import Header from "../(components)/header"
import '@blocknote/core/fonts/inter.css';
import '@blocknote/mantine/style.css';
import { Inter, Noto_Sans, Brygada_1918 } from "next/font/google"; // Import fonts
import "../global.css";


// Configure the fonts
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" }); // Example base font
const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ['400', '700'], // Include weights you might need
  variable: "--font-noto-sans", // CSS variable for optional use
});
const brygada = Brygada_1918({
  subsets: ["latin"],
  weight: ['400', '700'], // Include weights you might need
  variable: "--font-brygada", // CSS variable for optional use
});

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function UserLayout({
    children,
  }: {
    children: React.ReactNode
  }) {

    return (
      <html lang="en">
        <body className={`${inter.variable} ${notoSans.variable} ${brygada.variable} ${notoSans.className}`}>
          <Header />
          {children}
          </body>
      </html>
    )
  }
  